//  API.swift
//  CountryFacts
//
//  This file is automatically generated by Apollo iOS SDK.
//  Do not edit manually.
//
//  Generated on: Auto-generated
//  © 2025 Coding With Amit. All rights reserved.

// This file serves as a convenience import for all generated Apollo types.
// The actual generated code is in the Schema/ and Operations/ directories.

@_exported import ApolloAPI
